[package]
name = "kanoodle-solver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.9.0"
structopt = "0.3.25"
paste = "1.0.6"
arrayvec = "0.7.2"
atty = "0.2.14"
